### ISSUE TITLE
Please retain the Cellpose copyright as required by the BSD-3 license

### ISSUE THREAD

**Issue by marius10p** [xzhang0123/SwinCell#1]
The Cellpose license (BSD-3) is very permissive. However, it requires you to retain the copyright notice [here](https://github.com/MouseLand/cellpose?tab=BSD-3-Clause-1-ov-file) when you copy portions of the code.

The copyright notice must be maintained and distributed with every copy of your codebase.

In addition, we ask that you include this copyright statement at the top of your file:
"""
Copyright © 2022 Howard Hughes Medical Institute, Authored by Carsen Stringer and Marius Pachitariu.
"""

Thank you.

**Comment by xzhang0123** [comment]
Thank you for the clarification regarding the BSD-3 license requirements. We have updated the LICENSE file to include the copyright notice and proper attribution for the portions of code We’ve used from the Cellpose project.

**Comment by marius10p** [comment]
Great, thanks!
